language: node_js
dist: trusty

node_js:
  - "6"

env:
  - PUBLISH_DIR=$TRAVIS_BUILD_DIR/gh-pages

addons:
  organization: cychop-github
  sonarqube:
    token: $SONARQUBE_TOKEN
  branches:
    - master

cache:
  directories:
    - node
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/.bin:$PATH
  - yarn global add gulp-cli

install:
  - yarn install

# start virtual display for testing
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp ci
  - sonar-scanner

# deploy to Github Pages if build was successful
after_success: |
  if [ $TRAVIS_BRANCH == 'master' -a $TRAVIS_PUBLISH_PAGES == 'true' -a -n $GITHUB_API_KEY ]; then
    git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch gh-pages "$PUBLISH_DIR"
    make publish
    cd "$PUBLISH_DIR"
    git add --all
    git -c user.name='Travis CI' -c user.email='travis' commit -m "Travis build $TRAVIS_BUILD_NUMBER"
    git push -q https://cyChop:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git
    cd $TRAVIS_BUILD_DIR
  fi
