language: node_js
node_js:
  - "5"

env:
  - PUBLISH_DIR=$TRAVIS_BUILD_DIR/gh-pages

before_script:
  - npm install -g gulp
script: gulp ci
after_success: |
  if [ $TRAVIS_BRANCH == 'master' -a $TRAVIS_PUBLISH_PAGES == 'true' -a -n $GITHUB_API_KEY ]; then
    git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch gh-pages "$PUBLISH_DIR"
    make publish
    cd "$PUBLISH_DIR"
    git add --all
    git -c user.name='Travis CI' -c user.email='travis' commit -m "Travis build $TRAVIS_BUILD_NUMBER"
    git push -q https://cyChop:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git
    cd $TRAVIS_BUILD_DIR
  fi

