language: node_js
dist: trusty

node_js:
  - "6"

env:
  - PUBLISH_DIR=$TRAVIS_BUILD_DIR/gh-pages

addons:
  organization: cychop-github
  sonarcloud:
    token: $SONARQUBE_TOKEN
    branches:
      - master

#cache:
#  yarn: true
#  directories:
#    - node_modules

install:
  - yarn install

# start virtual display for testing
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node node_modules/gulp/bin/gulp.js --color ci

# deploy to Github Pages if build was successful
after_success:
  - sonar-scanner
  - chmod +x .publish.sh
  - ./.publish.sh
